### ISSUE TITLE
TypeError: undefined is not a function (evaluation 'remoteModules.forEach')

### ISSUE THREAD

**Issue by NicolasDuran** [7kfpun/FinanceReactNative#13]
I use react-native: 0.26.3

I done the following setup 
```
git clone git@github.com:7kfpun/FinanceReactNative.git
cd FinanceReactNative
run npm install
```

When the app start, I automatically get a red screen with :
`TypeError: undefined is not a function (evaluation 'remoteModules.forEach')`

What can I do ?

**Comment by 7kfpun** [comment]
I suggest you try again with all packages fixed to the old version (removing sign ^).

I would make a big update to the latest react-native later.
