### ISSUE TITLE
咨询在android中的运行故障

### ISSUE THREAD

**Issue by waynexu110** [7kfpun/FinanceReactNative#14]
你好，根据readme的步骤在android 4.4真机和android 5.0 的genymotion模拟器中安装调试，过程中一切正常并无错误提示，但最后在app安装完毕启动时均显示程序已停止运行。更奇怪的是在chrome的开发者工具中打开所在目录也会导致开发者工具在无提示情况下直接意外关闭。
请问，在android平台中是否有其他注意事项？
十分感谢！

**Comment by 7kfpun** [comment]
Fixed, thanks for report!

https://github.com/7kfpun/FinanceReactNative/commit/574cad3b9b182db1dba9aa40f4e036aea0f57c22
