### ISSUE TITLE
For some reason, it only brings up the iphone emulator, and not the app

### ISSUE THREAD

**Issue by ShayanJa** [7kfpun/FinanceReactNative#16]
What configutation should i have to run this? I have React-native. and npm

**Comment by 7kfpun** [comment]
Should be fixed with this commit https://github.com/7kfpun/FinanceReactNative/commit/c4909abfafb6b667328f570304d4dc02cd587403 (https://github.com/7kfpun/FinanceReactNative/issues/15).
