### ISSUE TITLE
react-native依赖问题

### ISSUE THREAD

**Issue by lishoulong** [7kfpun/FinanceReactNative#18]
"react-native": "0.38.0",should change the version of it top than 0.38.0, or it will build fail, and alert the following errors:
“SyntaxError: Strict mode does not allow function declarations in a lexically nested statement ”。

And can you give me the permission to create new branch(for example dev or bug branch;),so I can apply merge request.

**Comment by 7kfpun** [comment]
You can fork it and request a pull request.

**Comment by 7kfpun** [comment]
Just tested, I think I would update the version to 0.42.0.

**Comment by lishoulong** [comment]
ok，thanks
