### ISSUE TITLE
Multiple errors on app launch in iOS Simulator

### ISSUE THREAD

**Issue by SKempin** [7kfpun/FinanceReactNative#21]
Receiving multiple errors on  iOS Simulator:

<img width="361" alt="screen shot 2017-05-31 at 11 17 19" src="https://cloud.githubusercontent.com/assets/10877466/26627603/f56d8e74-45f2-11e7-82a9-f831b7f80d02.png">

**Comment by 7kfpun** [comment]
If you update React Native, you have to update the dependencies as well as the breaking changes.

**Comment by 7kfpun** [comment]
This commit should fix.

https://github.com/7kfpun/FinanceReactNative/commit/0f943ccbd2f11eb826c3740dbe4109aeaa7f4682
