### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by acarterczyzewicz** [7kfpun/FinanceReactNative#22]
Running on React, I need an app.js file. Is there a video or tutorial on compiling this?

**Comment by 7kfpun** [comment]
It's for React Native. You need either Xcode or Android.

**Comment by acarterczyzewicz** [comment]
I have android but need to know how to compile this and build the apk. Is there a tutorial or docs?

**Comment by 7kfpun** [comment]
https://facebook.github.io/react-native/docs/getting-started.html

https://github.com/7kfpun/FinanceReactNative#running

**Comment by acarterczyzewicz** [comment]
symbol:   class ReactNativeHost
  location: class MainApplication
C:\new_projects\FinanceApp\android\app\src\main\java\com\finance\MainApplication.java:32: error: method does not override or implement a method from a supertype
  @Override
  ^
8 errors
:app:compileDebugJavaWithJavac FAILED

**Comment by 7kfpun** [comment]
Maybe you could try building a new project `react-native init AwesomeProject` and run it first.
I think your issue has nothing to do with the project.
