### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by shangcloud** [7kfpun/FinanceReactNative#8]
npm ERR! peerinvalid The package react@15.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-tween-state@0.1.4 wants react@>=0.14
npm ERR! peerinvalid Peer react-dom@0.14.8 wants react@^0.14.8

npm install fail

**Comment by 7kfpun** [comment]
Did you install with react-native@0.18.0? It should be work if you stick with this version.

**Comment by ajnudnyy** [comment]
I have faced this issue almost, when I had tried to launch app , I got an error

Error: connot find module './packager/babelRegisterOnly'
I was wandering if the early version of react-native caused this.

version info:
xcode v7.3
npm 2.15.0
react-native 0.18.0

**Comment by 7kfpun** [comment]
Could you try fix the version of all packages by removing **^** ?

**Comment by 7kfpun** [comment]
Rewrite with react-native 0.26.3, please try if it works.
